#!/usr/bin/env bash
set -euo pipefail
task_root="${RUSPLADDER_WORK_ROOT:-/home/wubw/data/ruspladder}"
repo_root=$(cd "$(dirname "$0")/.." && pwd)
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 NUMBA_NUM_THREADS=4 RAYON_NUM_THREADS=4
export NUMBA_CACHE_DIR="$task_root/cache/numba"
export TMPDIR="$task_root/tmp"
cd "$repo_root"
scripts/cargo.sh fmt -- --check
scripts/cargo.sh clippy --all-targets -- -D warnings
scripts/cargo.sh build --examples --bin ruspladder
check_root="$task_root/runs/check-$(date +%Y%m%dT%H%M%S)"
mkdir -p "$check_root"
printf 'Evidence directory: %s\n' "$check_root"
reference_python="$task_root/envs/reference/bin/python"
probe_root="$task_root/target/debug/examples"
upstream="$task_root/upstream/spladder"
"$reference_python" scripts/compare_graphs.py "$probe_root/graph_probe" --failure "$check_root/graph-mismatch.json"
"$reference_python" scripts/compare_annotations.py "$probe_root/annotation_probe" --upstream "$upstream" --work "$check_root/annotation" --extra "$task_root/fixtures/airway/Homo_sapiens.GRCh37.75_subset.gtf"
"$reference_python" scripts/compare_reads.py "$probe_root/reads_probe" --upstream "$upstream" --work "$check_root/reads"
"$reference_python" scripts/compare_detectors.py "$probe_root/detect_probe" --upstream "$upstream" --work "$check_root/detectors"
"$reference_python" scripts/compare_collection.py "$probe_root/collect_probe" --upstream "$upstream" --work "$check_root/collection"
"$reference_python" scripts/compare_edits.py "$probe_root/edit_probe" --upstream "$upstream" --work "$check_root/edits"
"$reference_python" scripts/compare_augmentation.py "$probe_root/augment_probe" --upstream "$upstream" --work "$check_root/augmentation"
"$reference_python" scripts/compare_intron_edges.py "$probe_root/intron_probe" --upstream "$upstream" --work "$check_root/introns"
"$reference_python" scripts/compare_intron_filters.py "$probe_root/intron_filter_probe" --work "$check_root/intron-filters"
"$reference_python" scripts/compare_build_graphs.py "$probe_root/build_graph_probe" --upstream "$upstream" --work "$check_root/build-graphs" --airway "$task_root/fixtures/airway"
"$reference_python" scripts/compare_build_sequence.py "$probe_root/build_sequence_probe" --work "$check_root/build-sequence"
"$reference_python" scripts/compare_merge.py "$probe_root/merge_probe" --upstream "$upstream" --work "$check_root/merge"
"$reference_python" scripts/compare_counts.py "$probe_root/count_probe" --upstream "$upstream" --work "$check_root/counts"
"$reference_python" scripts/compare_verification.py "$probe_root/verify_probe" --upstream "$upstream" --work "$check_root/verification"
"$reference_python" scripts/compare_count_io.py "$probe_root/count_io_probe" "$probe_root/normalization_probe" --upstream "$upstream" --work "$check_root/count-io"
"$reference_python" scripts/compare_count_collect.py "$probe_root/count_collect_probe" --counts "$check_root/count-io" --work "$check_root/count-collect"
"$reference_python" scripts/compare_analysis.py "$probe_root/analyze_probe" --upstream "$upstream" --work "$check_root/analysis"
"$reference_python" scripts/compare_outputs.py "$probe_root/output_probe" --upstream "$upstream" --analysis "$check_root/analysis" --work "$check_root/outputs"
"$reference_python" scripts/compare_quantify.py "$probe_root/quantify_probe" --upstream "$upstream" --analysis "$check_root/analysis" --work "$check_root/quantify"
"$reference_python" scripts/compare_correction.py "$probe_root/correction_probe" --work "$check_root/correction"
"$reference_python" scripts/compare_glm.py "$probe_root/glm_probe" --work "$check_root/glm"
"$reference_python" scripts/compare_optimize.py "$probe_root/optimize_probe" --work "$check_root/optimize"
"$reference_python" scripts/compare_likelihood.py "$probe_root/likelihood_probe" --work "$check_root/likelihood"
"$reference_python" scripts/compare_statistics.py "$probe_root/statistics_probe" --work "$check_root/statistics"
"$reference_python" scripts/compare_test_input.py "$probe_root/test_input_probe" --work "$check_root/test-input"
"$reference_python" scripts/compare_test_output.py "$probe_root/test_output_probe" --upstream "$upstream" --work "$check_root/test-output"
"$reference_python" scripts/compare_test_cli.py "$task_root/target/debug/ruspladder" "$probe_root/import_fixture_probe" --upstream "$upstream" --work "$check_root/test-cli"
"$reference_python" scripts/compare_test_cli_synthetic.py "$task_root/target/debug/ruspladder" "$probe_root/import_fixture_probe" --upstream "$upstream" --work "$check_root/test-cli-six"
