#!/usr/bin/env python3
"""Compare actual upstream event collection/curation and 1/4-thread Rust runs."""
import argparse
import contextlib
import io
import json
import pickle
import subprocess
from pathlib import Path
from types import SimpleNamespace

from spladder.alt_splice.collect import collect_events
from compare_annotations import serialize

KINDS = ["exon_skip", "intron_retention", "alt_3prime", "alt_5prime", "mult_exon_skip", "mutex_exons"]


def event_json(event):
    value = {"event_type": event.event_type, "chr": event.chr, "strand": event.strand,
             "exons1": event.exons1.tolist(), "exons2": event.exons2.tolist(),
             "gene_name": event.gene_name.tolist(), "gene_idx": int(event.gene_idx),
             "id": int(event.id), "annotated": int(event.annotated)}
    return {"event": value, "coords": event.get_coords().tolist(),
            "inner_coords": event.get_inner_coords().tolist(), "introns": event.get_introns().tolist(),
            "span": int(event.get_len()), "coordinate_strings": list(event.get_exon_coordinate_strings())}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("probe", type=Path)
    parser.add_argument("--upstream", type=Path, required=True)
    parser.add_argument("--work", type=Path, required=True)
    args = parser.parse_args()
    args.work.mkdir(parents=True, exist_ok=True)
    sources = sorted((args.upstream / "tests").glob("*/results*/spladder/genes_graph_conf3.merge_graphs.pickle"))
    # Include a hand-specified multi-skip graph via the upstream gene class, as
    # the repository's standard merged fixtures have no multiple-skip events.
    import numpy as np
    from spladder.classes.gene import Gene
    from spladder.classes.splicegraph import Splicegraph
    gene = Gene(name="multi", start=10, stop=200, chr="chr1", strand="+")
    gene.transcripts = ["long", "short"]
    gene.exons = [np.array([[10, 30], [60, 80], [110, 130], [180, 200]]), np.array([[10, 30], [180, 200]])]
    gene.splicegraph = Splicegraph(gene)
    gene.populate_annotated_introns()
    gene.label_alt()
    gene.to_sparse()
    multiple = args.work / "multiple.pickle"
    with multiple.open("wb") as output: pickle.dump((np.array([gene], dtype=object), {}), output)
    sources.append(multiple)
    requests, expected = [], []
    totals = {kind: 0 for kind in KINDS}
    for source_index, source in enumerate(sources):
        with source.open("rb") as handle: genes = pickle.load(handle, encoding="latin1")[0]
        for gene in genes:
            gene.from_sparse()
            if not hasattr(gene, "introns_anno"): gene.populate_annotated_introns()
        chromosomes = {chromosome: i for i, chromosome in enumerate(sorted({g.chr for g in genes}))}
        for curate in [False, True]:
            outdir = args.work / f"reference-{source_index}-{int(curate)}"
            outdir.mkdir(exist_ok=True)
            # Remove only outputs generated by this comparison, so changing a
            # reference option cannot silently reuse another option's pickle.
            for kind in KINDS:
                (outdir / f"merge_graphs_{kind}_C3.pickle").unlink(missing_ok=True)
            options = SimpleNamespace(samples=["sample"], confidence=3, merge="merge_graphs",
                                      spladderfile=str(source), outdir=str(outdir), event_types=KINDS,
                                      parallel=1, verbose=False, detect_edge_limit=500,
                                      chrm_lookup=chromosomes, curate_alt_prime=curate)
            with contextlib.redirect_stdout(io.StringIO()): collect_events(options)
            found = {}
            for kind in KINDS:
                with (outdir / f"merge_graphs_{kind}_C3.pickle").open("rb") as handle: events = pickle.load(handle)
                found[kind] = [event_json(event) for event in events]
                totals[kind] += len(events)
            for parallel in [1, 4]:
                requests.append({"genes": [serialize(gene) for gene in genes], "chromosomes": chromosomes,
                                 "edge_limit": 500, "curate": curate, "parallel": parallel})
                expected.append(found)
    result = subprocess.run([str(args.probe)], input="".join(json.dumps(r) + "\n" for r in requests),
                            text=True, stdout=subprocess.PIPE, check=True)
    actual = [json.loads(line) for line in result.stdout.splitlines()]
    assert len(actual) == len(expected)
    for index, (want, got) in enumerate(zip(expected, actual)):
        if want != got:
            failure = args.work / "mismatch.json"
            failure.write_text(json.dumps({"case": index, "expected": want, "actual": got}, indent=2))
            raise AssertionError(f"event collection mismatch: {failure}")
    assert all(count > 0 for count in totals.values()), totals
    report = {"cases": len(actual), "curation_modes": [False, True], "threads": [1, 4],
              "event_totals": totals, "result": "pass"}
    (args.work / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    print(f"PASS: {len(actual)} event collection cases, curation on/off, 1/4 threads; {totals}")


if __name__ == "__main__":
    main()
