//! SplAdder v3.1.1 algorithms, migrated to Rust.
pub mod analyze;
pub mod annotation;
pub mod annotation_loci;
pub mod augment;
pub mod build_cli;
pub mod build_graph;
pub mod cache;
pub mod correction;
pub mod count;
pub mod count_io;
pub mod detect;
pub mod editgraph;
pub mod events;
pub mod expression;
pub mod glm;
pub mod graph;
pub mod hdf5io;
pub mod intron_edges;
pub mod introns;
pub mod likelihood;
mod linalg;
pub mod merge;
pub mod numeric;
pub mod optimize;
pub mod output;
pub mod prep;
pub mod quantify;
pub mod reads;
pub mod reference;
mod sort;
pub mod sparse;
pub mod statistics;
pub mod test_cli;
pub mod test_output;
pub mod testing;
pub mod verify;
